Character.create!(name:"Professor Longfellow")

Stat.create!(name:"Speed")
Stat.create!(name:"Might")
Stat.create!(name:"Sanity")
Stat.create!(name:"Knowledge")

CharacterStat.create!(character_id: 1, stat_id: 1, level: 0, value: 0)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 1, value: 2)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 2, value: 2)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 3, value: 4)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 4, value: 4)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 5, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 6, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 7, value: 6)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 8, value: 6)

CharacterStat.create!(character_id: 1, stat_id: 2, level: 0, value: 0)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 1, value: 1)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 2, value: 2)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 3, value: 3)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 4, value: 4)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 5, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 6, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 7, value: 6)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 8, value: 6)

CharacterStat.create!(character_id: 1, stat_id: 3, level: 0, value: 0)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 1, value: 1)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 2, value: 2)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 3, value: 3)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 4, value: 4)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 5, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 6, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 7, value: 6)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 8, value: 7)

CharacterStat.create!(character_id: 1, stat_id: 4, level: 0, value: 0)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 1, value: 4)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 2, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 3, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 4, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 5, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 6, value: 6)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 7, value: 7)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 8, value: 8)

Character.create!(name: "Madame Zostra")
Character.create!(name: "Ox Bellows")
Character.create!(name: "Zoe Ingstrom")
