Hobby1.create!(name: "Coloring")
Hobby1.create!(name: "Astrology")
Hobby1.create!(name: "Badminton")
Hobby1.create!(name: "Taxidermy")
Hobby1.create!(name: "Juggling")
Hobby1.create!(name: "Writing")
Hobby1.create!(name: "Botany")
Hobby1.create!(name: "Board Games")
Hobby1.create!(name: "Cooking")
Hobby1.create!(name: "Cryptography")
Hobby1.create!(name: "Magic")
Hobby1.create!(name: "Geocaching")

Hobby2.create!(name: "Macrame")
Hobby2.create!(name: "Fishing")
Hobby2.create!(name: "Golf")
Hobby2.create!(name: "Scuba Diving")
Hobby2.create!(name: "Origami")
Hobby2.create!(name: "Surfing")
Hobby2.create!(name: "Woodworking")
Hobby2.create!(name: "Cycling")
Hobby2.create!(name: "Curling")
Hobby2.create!(name: "Martial Arts")
Hobby2.create!(name: "Knife Making")
Hobby2.create!(name: "Weight Lifting")

Character.create!(name:"Professor Longfellow")

Stat.create!(name:"Speed")
Stat.create!(name:"Might")
Stat.create!(name:"Sanity")
Stat.create!(name:"Knowledge")

CharacterStat.create!(character_id: 1, stat_id: 1, level: 0, value: 0)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 1, value: 2)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 2, value: 2)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 3, value: 4)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 4, value: 4)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 5, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 6, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 7, value: 6)
CharacterStat.create!(character_id: 1, stat_id: 1, level: 8, value: 6)

CharacterStat.create!(character_id: 1, stat_id: 2, level: 0, value: 0)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 1, value: 1)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 2, value: 2)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 3, value: 3)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 4, value: 4)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 5, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 6, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 7, value: 6)
CharacterStat.create!(character_id: 1, stat_id: 2, level: 8, value: 6)

CharacterStat.create!(character_id: 1, stat_id: 3, level: 0, value: 0)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 1, value: 1)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 2, value: 2)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 3, value: 3)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 4, value: 4)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 5, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 6, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 7, value: 6)
CharacterStat.create!(character_id: 1, stat_id: 3, level: 8, value: 7)

CharacterStat.create!(character_id: 1, stat_id: 4, level: 0, value: 0)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 1, value: 4)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 2, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 3, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 4, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 5, value: 5)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 6, value: 6)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 7, value: 7)
CharacterStat.create!(character_id: 1, stat_id: 4, level: 8, value: 8)

Character.create!(name: "Madame Zostra")
Character.create!(name: "Ox Bellows")
Character.create!(name: "Zoe Ingstrom")
